/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
export interface UserId {
  id: string;
}

export interface User {
  email: string;
  id: string;
  name: string;
}

