openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
servers:
  - url: "{protocol}://localhost:{port}"
    variables:
      protocol:
        default: "http"
        enum:
          - "http"
          - "https"
      port:
        default: "8080"

paths:
  /users:
    get:
      summary: Get all users
      operationId: listUsers
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /users/{userId}:
    get:
      summary: Get a user
      operationId: showUserById
      parameters:
        - in: path
          name: userId
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      summary: Update a user
      operationId: updateUserById
      parameters:
        - in: path
          name: userId
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: User updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      summary: Delete a user
      operationId: deleteUserById
      parameters:
        - $ref: "#/components/parameters/UserId"
      responses:
        204:
          description: 成功
        400:
          description: 不正なパラメータ
        404:
          description: 該当ユーザーなし
        500:
          description: 内部エラー

components:
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      description: User identifier
      schema:
        type: string
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
      example:
        id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        name: "John Doe"
        email: "john.doe@example.com"
